// /////////////////////////////////////////////////////////////////
// Generated by dtkTestGenerator
// /////////////////////////////////////////////////////////////////

#include "%1.h"

%1Object::%1Object(void)
{
}

%1Object::~%1Object(void)
{
}

void %1Object::initTestCase()
{
}

void %1Object::init()
{
}

void %1Object::cleanup()
{
}

void %1Object::cleanupTestCase()
{
}

/*
void %1Object::testFoo_data()
{
}
*/

void %1Object::testFoo()
{
    QVERIFY(true==false);
}

/**
   DTKTEST_NOGUI_MAIN will create the entry point without running
   a window manager (such as X on linux). If you need one, change
   it to DTKTEST_MAIN().
 **/
DTKTEST_NOGUI_MAIN(%1,%1Object)
