// /////////////////////////////////////////////////////////////////
// Generated by dtkTestGenerator
// /////////////////////////////////////////////////////////////////

#include "%1.h"

%1::%1(void)
{

}

%1::~%1(void)
{
}

void %1::initTestCase()
{
}

void %1::init()
{
}

void %1::cleanup()
{
}

void %1::cleanupTestCase()
{
}

/*
void %1::testFoo_data()
{
}
*/

void %1::testFoo()
{
    QVERIFY(true==false);
}

/**
   QTEST_APPLESS_MAIN will create the entry point without running
   a window manager (such as X on linux). If you need one, change
   it to QTEST_MAIN().
 **/
QTEST_APPLESS_MAIN(%1)
