// /////////////////////////////////////////////////////////////////
// Generated by dtkTestGenerator
// /////////////////////////////////////////////////////////////////

#ifndef %2_H
#define %2_H

#include <dtkCore/dtkTest.h>

class %1Object : public QObject
{
    Q_OBJECT

public:
             %1Object(void);
    virtual ~%1Object(void);


private slots:
    void initTestCase(void);
    void init(void);
    void cleanup(void);
    void cleanupTestCase(void);

private slots:
    void testFoo();
};

#endif
