// /////////////////////////////////////////////////////////////////
// Generated by dtkTestGenerator
// /////////////////////////////////////////////////////////////////

#include "%1.h"

%1Object::%1Object(void)
{

}

%1Object::~%1Object(void)
{

}

void %1Object::initTestCase(void)
{

}

void %1Object::init(void)
{

}

void %1Object::cleanup(void)
{

}

void %1Object::cleanupTestCase(void)
{

}

//void %1Object::testFoo_data(void)
//{
//
//}

void %1Object::testFoo(void)
{
    QVERIFY(true==false);
}

DTKTEST%2_MAIN(%1,%1Object)
