// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef %1PLUGINCONFIG_H
#define %1PLUGINCONFIG_H

#define %2Plugin_VERSION_MAJOR @%2Plugin_VERSION_MAJOR@
#define %2Plugin_VERSION_MINOR @%2Plugin_VERSION_MINOR@
#define %2Plugin_VERSION_BUILD @%2Plugin_VERSION_BUILD@

#endif
